/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EntityId = IDL.Nat;
export const BookingType = IDL.Variant({
  'hotel' : IDL.Null,
  'guide' : IDL.Null,
});
export const CreateBookingInput = IDL.Record({
  'checkIn' : IDL.Text,
  'paymentTransactionId' : IDL.Opt(IDL.Text),
  'guestCount' : IDL.Nat,
  'referenceId' : EntityId,
  'bookingType' : BookingType,
  'checkOut' : IDL.Text,
  'paymentAmount' : IDL.Nat,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Booking = IDL.Record({
  'id' : EntityId,
  'status' : BookingStatus,
  'checkIn' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'referenceNumber' : IDL.Text,
  'paymentTransactionId' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'guestCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'referenceId' : EntityId,
  'bookingType' : BookingType,
  'checkOut' : IDL.Text,
  'paymentAmount' : IDL.Nat,
});
export const GuideSpecialization = IDL.Variant({
  'nature' : IDL.Null,
  'adventure' : IDL.Null,
  'general' : IDL.Null,
  'heritage' : IDL.Null,
});
export const CreateGuideInput = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'ratePerDay' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'specialization' : GuideSpecialization,
  'phoneNumber' : IDL.Text,
  'languagesSpoken' : IDL.Vec(IDL.Text),
});
export const Guide = IDL.Record({
  'id' : EntityId,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'ratePerDay' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'specialization' : GuideSpecialization,
  'phoneNumber' : IDL.Text,
  'languagesSpoken' : IDL.Vec(IDL.Text),
});
export const CreateHotelInput = IDL.Record({
  'starRating' : IDL.Nat,
  'imageUrls' : IDL.Vec(IDL.Text),
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'totalRooms' : IDL.Nat,
});
export const Hotel = IDL.Record({
  'id' : EntityId,
  'starRating' : IDL.Nat,
  'imageUrls' : IDL.Vec(IDL.Text),
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'totalRooms' : IDL.Nat,
});
export const PlaceCategory = IDL.Variant({
  'other' : IDL.Null,
  'viewpoint' : IDL.Null,
  'beach' : IDL.Null,
  'temple' : IDL.Null,
  'waterfall' : IDL.Null,
});
export const CreatePlaceInput = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'bestTimeToVisit' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'longitude' : IDL.Opt(IDL.Float64),
  'address' : IDL.Text,
  'category' : PlaceCategory,
});
export const Place = IDL.Record({
  'id' : EntityId,
  'latitude' : IDL.Opt(IDL.Float64),
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'bestTimeToVisit' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'longitude' : IDL.Opt(IDL.Float64),
  'address' : IDL.Text,
  'category' : PlaceCategory,
});
export const CreateRestaurantInput = IDL.Record({
  'ratingAverage' : IDL.Float64,
  'name' : IDL.Text,
  'cuisineTypes' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'priceRange' : IDL.Nat,
  'hoursOpen' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const Restaurant = IDL.Record({
  'id' : EntityId,
  'ratingAverage' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'cuisineTypes' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'priceRange' : IDL.Nat,
  'hoursOpen' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const CreateRoomTypeInput = IDL.Record({
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'hotelId' : EntityId,
  'description' : IDL.Text,
  'availability' : IDL.Nat,
  'maxGuests' : IDL.Nat,
});
export const RoomType = IDL.Record({
  'id' : EntityId,
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'hotelId' : EntityId,
  'description' : IDL.Text,
  'availability' : IDL.Nat,
  'maxGuests' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'totalBookings' : IDL.Nat,
  'totalRestaurants' : IDL.Nat,
  'totalHotels' : IDL.Nat,
  'totalGuides' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'pendingReviews' : IDL.Nat,
  'totalPlaces' : IDL.Nat,
});
export const ReviewTargetType = IDL.Variant({
  'hotel' : IDL.Null,
  'guide' : IDL.Null,
});
export const Review = IDL.Record({
  'id' : EntityId,
  'isApproved' : IDL.Bool,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'targetType' : ReviewTargetType,
  'rating' : IDL.Nat,
  'targetId' : EntityId,
});
export const SessionToken = IDL.Record({
  'token' : IDL.Text,
  'expiresAt' : Timestamp,
  'username' : IDL.Text,
  'userId' : IDL.Principal,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
});
export const UpdateGuideInput = IDL.Record({
  'id' : EntityId,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'ratePerDay' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'specialization' : GuideSpecialization,
  'phoneNumber' : IDL.Text,
  'languagesSpoken' : IDL.Vec(IDL.Text),
});
export const UpdateHotelInput = IDL.Record({
  'id' : EntityId,
  'starRating' : IDL.Nat,
  'imageUrls' : IDL.Vec(IDL.Text),
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'totalRooms' : IDL.Nat,
});
export const UpdatePlaceInput = IDL.Record({
  'id' : EntityId,
  'latitude' : IDL.Opt(IDL.Float64),
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'bestTimeToVisit' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'longitude' : IDL.Opt(IDL.Float64),
  'address' : IDL.Text,
  'category' : PlaceCategory,
});

export const idlService = IDL.Service({
  'approveReview' : IDL.Func([EntityId], [IDL.Bool], []),
  'cancelBooking' : IDL.Func([EntityId], [IDL.Bool], []),
  'claimAdmin' : IDL.Func([], [IDL.Bool], []),
  'confirmBookingPayment' : IDL.Func(
      [EntityId, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'createBooking' : IDL.Func([CreateBookingInput], [Booking], []),
  'createGuide' : IDL.Func([CreateGuideInput], [Guide], []),
  'createHotel' : IDL.Func([CreateHotelInput], [Hotel], []),
  'createPlace' : IDL.Func([CreatePlaceInput], [Place], []),
  'createRestaurant' : IDL.Func([CreateRestaurantInput], [Restaurant], []),
  'createRoomType' : IDL.Func([CreateRoomTypeInput], [RoomType], []),
  'deleteGuide' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteHotel' : IDL.Func([EntityId], [IDL.Bool], []),
  'deletePlace' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteRestaurant' : IDL.Func([EntityId], [IDL.Bool], []),
  'getBooking' : IDL.Func([EntityId], [IDL.Opt(Booking)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], []),
  'getGuide' : IDL.Func([EntityId], [IDL.Opt(Guide)], ['query']),
  'getHotel' : IDL.Func([EntityId], [IDL.Opt(Hotel)], ['query']),
  'getPlace' : IDL.Func([EntityId], [IDL.Opt(Place)], ['query']),
  'getRestaurant' : IDL.Func([EntityId], [IDL.Opt(Restaurant)], ['query']),
  'getReviewsForTarget' : IDL.Func(
      [ReviewTargetType, EntityId],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getRoomTypesForHotel' : IDL.Func([EntityId], [IDL.Vec(RoomType)], ['query']),
  'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
  'listFeaturedPlaces' : IDL.Func([], [IDL.Vec(Place)], ['query']),
  'listFeaturedRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'listGuides' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
  'listHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
  'listPendingReviews' : IDL.Func([], [IDL.Vec(Review)], []),
  'listPlaces' : IDL.Func([], [IDL.Vec(Place)], ['query']),
  'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text })],
      [],
    ),
  'logoutUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'rejectReview' : IDL.Func([EntityId], [IDL.Bool], []),
  'searchGuides' : IDL.Func(
      [IDL.Text, IDL.Opt(GuideSpecialization)],
      [IDL.Vec(Guide)],
      ['query'],
    ),
  'searchHotels' : IDL.Func([IDL.Text], [IDL.Vec(Hotel)], ['query']),
  'searchPlaces' : IDL.Func(
      [IDL.Text, IDL.Opt(PlaceCategory)],
      [IDL.Vec(Place)],
      ['query'],
    ),
  'searchRestaurants' : IDL.Func([IDL.Text], [IDL.Vec(Restaurant)], ['query']),
  'updateGuide' : IDL.Func([UpdateGuideInput], [IDL.Bool], []),
  'updateHotel' : IDL.Func([UpdateHotelInput], [IDL.Bool], []),
  'updatePlace' : IDL.Func([UpdatePlaceInput], [IDL.Bool], []),
  'validateSession' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EntityId = IDL.Nat;
  const BookingType = IDL.Variant({ 'hotel' : IDL.Null, 'guide' : IDL.Null });
  const CreateBookingInput = IDL.Record({
    'checkIn' : IDL.Text,
    'paymentTransactionId' : IDL.Opt(IDL.Text),
    'guestCount' : IDL.Nat,
    'referenceId' : EntityId,
    'bookingType' : BookingType,
    'checkOut' : IDL.Text,
    'paymentAmount' : IDL.Nat,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Booking = IDL.Record({
    'id' : EntityId,
    'status' : BookingStatus,
    'checkIn' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'referenceNumber' : IDL.Text,
    'paymentTransactionId' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'guestCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'referenceId' : EntityId,
    'bookingType' : BookingType,
    'checkOut' : IDL.Text,
    'paymentAmount' : IDL.Nat,
  });
  const GuideSpecialization = IDL.Variant({
    'nature' : IDL.Null,
    'adventure' : IDL.Null,
    'general' : IDL.Null,
    'heritage' : IDL.Null,
  });
  const CreateGuideInput = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'ratePerDay' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'specialization' : GuideSpecialization,
    'phoneNumber' : IDL.Text,
    'languagesSpoken' : IDL.Vec(IDL.Text),
  });
  const Guide = IDL.Record({
    'id' : EntityId,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'ratePerDay' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'specialization' : GuideSpecialization,
    'phoneNumber' : IDL.Text,
    'languagesSpoken' : IDL.Vec(IDL.Text),
  });
  const CreateHotelInput = IDL.Record({
    'starRating' : IDL.Nat,
    'imageUrls' : IDL.Vec(IDL.Text),
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'totalRooms' : IDL.Nat,
  });
  const Hotel = IDL.Record({
    'id' : EntityId,
    'starRating' : IDL.Nat,
    'imageUrls' : IDL.Vec(IDL.Text),
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'totalRooms' : IDL.Nat,
  });
  const PlaceCategory = IDL.Variant({
    'other' : IDL.Null,
    'viewpoint' : IDL.Null,
    'beach' : IDL.Null,
    'temple' : IDL.Null,
    'waterfall' : IDL.Null,
  });
  const CreatePlaceInput = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'bestTimeToVisit' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'longitude' : IDL.Opt(IDL.Float64),
    'address' : IDL.Text,
    'category' : PlaceCategory,
  });
  const Place = IDL.Record({
    'id' : EntityId,
    'latitude' : IDL.Opt(IDL.Float64),
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'bestTimeToVisit' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'longitude' : IDL.Opt(IDL.Float64),
    'address' : IDL.Text,
    'category' : PlaceCategory,
  });
  const CreateRestaurantInput = IDL.Record({
    'ratingAverage' : IDL.Float64,
    'name' : IDL.Text,
    'cuisineTypes' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'priceRange' : IDL.Nat,
    'hoursOpen' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const Restaurant = IDL.Record({
    'id' : EntityId,
    'ratingAverage' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'cuisineTypes' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'priceRange' : IDL.Nat,
    'hoursOpen' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const CreateRoomTypeInput = IDL.Record({
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'hotelId' : EntityId,
    'description' : IDL.Text,
    'availability' : IDL.Nat,
    'maxGuests' : IDL.Nat,
  });
  const RoomType = IDL.Record({
    'id' : EntityId,
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'hotelId' : EntityId,
    'description' : IDL.Text,
    'availability' : IDL.Nat,
    'maxGuests' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'totalBookings' : IDL.Nat,
    'totalRestaurants' : IDL.Nat,
    'totalHotels' : IDL.Nat,
    'totalGuides' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'pendingReviews' : IDL.Nat,
    'totalPlaces' : IDL.Nat,
  });
  const ReviewTargetType = IDL.Variant({
    'hotel' : IDL.Null,
    'guide' : IDL.Null,
  });
  const Review = IDL.Record({
    'id' : EntityId,
    'isApproved' : IDL.Bool,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'targetType' : ReviewTargetType,
    'rating' : IDL.Nat,
    'targetId' : EntityId,
  });
  const SessionToken = IDL.Record({
    'token' : IDL.Text,
    'expiresAt' : Timestamp,
    'username' : IDL.Text,
    'userId' : IDL.Principal,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
  });
  const UpdateGuideInput = IDL.Record({
    'id' : EntityId,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'ratePerDay' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'specialization' : GuideSpecialization,
    'phoneNumber' : IDL.Text,
    'languagesSpoken' : IDL.Vec(IDL.Text),
  });
  const UpdateHotelInput = IDL.Record({
    'id' : EntityId,
    'starRating' : IDL.Nat,
    'imageUrls' : IDL.Vec(IDL.Text),
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'totalRooms' : IDL.Nat,
  });
  const UpdatePlaceInput = IDL.Record({
    'id' : EntityId,
    'latitude' : IDL.Opt(IDL.Float64),
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'bestTimeToVisit' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'longitude' : IDL.Opt(IDL.Float64),
    'address' : IDL.Text,
    'category' : PlaceCategory,
  });
  
  return IDL.Service({
    'approveReview' : IDL.Func([EntityId], [IDL.Bool], []),
    'cancelBooking' : IDL.Func([EntityId], [IDL.Bool], []),
    'claimAdmin' : IDL.Func([], [IDL.Bool], []),
    'confirmBookingPayment' : IDL.Func(
        [EntityId, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'createBooking' : IDL.Func([CreateBookingInput], [Booking], []),
    'createGuide' : IDL.Func([CreateGuideInput], [Guide], []),
    'createHotel' : IDL.Func([CreateHotelInput], [Hotel], []),
    'createPlace' : IDL.Func([CreatePlaceInput], [Place], []),
    'createRestaurant' : IDL.Func([CreateRestaurantInput], [Restaurant], []),
    'createRoomType' : IDL.Func([CreateRoomTypeInput], [RoomType], []),
    'deleteGuide' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteHotel' : IDL.Func([EntityId], [IDL.Bool], []),
    'deletePlace' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteRestaurant' : IDL.Func([EntityId], [IDL.Bool], []),
    'getBooking' : IDL.Func([EntityId], [IDL.Opt(Booking)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], []),
    'getGuide' : IDL.Func([EntityId], [IDL.Opt(Guide)], ['query']),
    'getHotel' : IDL.Func([EntityId], [IDL.Opt(Hotel)], ['query']),
    'getPlace' : IDL.Func([EntityId], [IDL.Opt(Place)], ['query']),
    'getRestaurant' : IDL.Func([EntityId], [IDL.Opt(Restaurant)], ['query']),
    'getReviewsForTarget' : IDL.Func(
        [ReviewTargetType, EntityId],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getRoomTypesForHotel' : IDL.Func(
        [EntityId],
        [IDL.Vec(RoomType)],
        ['query'],
      ),
    'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
    'listFeaturedPlaces' : IDL.Func([], [IDL.Vec(Place)], ['query']),
    'listFeaturedRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'listGuides' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
    'listHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
    'listPendingReviews' : IDL.Func([], [IDL.Vec(Review)], []),
    'listPlaces' : IDL.Func([], [IDL.Vec(Place)], ['query']),
    'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text })],
        [],
      ),
    'logoutUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'rejectReview' : IDL.Func([EntityId], [IDL.Bool], []),
    'searchGuides' : IDL.Func(
        [IDL.Text, IDL.Opt(GuideSpecialization)],
        [IDL.Vec(Guide)],
        ['query'],
      ),
    'searchHotels' : IDL.Func([IDL.Text], [IDL.Vec(Hotel)], ['query']),
    'searchPlaces' : IDL.Func(
        [IDL.Text, IDL.Opt(PlaceCategory)],
        [IDL.Vec(Place)],
        ['query'],
      ),
    'searchRestaurants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'updateGuide' : IDL.Func([UpdateGuideInput], [IDL.Bool], []),
    'updateHotel' : IDL.Func([UpdateHotelInput], [IDL.Bool], []),
    'updatePlace' : IDL.Func([UpdatePlaceInput], [IDL.Bool], []),
    'validateSession' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };