/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : EntityId,
  'status' : BookingStatus,
  'checkIn' : string,
  'paymentStatus' : PaymentStatus,
  'referenceNumber' : string,
  'paymentTransactionId' : [] | [string],
  'userId' : UserId,
  'guestCount' : bigint,
  'createdAt' : Timestamp,
  'referenceId' : EntityId,
  'bookingType' : BookingType,
  'checkOut' : string,
  'paymentAmount' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type BookingType = { 'hotel' : null } |
  { 'guide' : null };
export interface CreateBookingInput {
  'checkIn' : string,
  'paymentTransactionId' : [] | [string],
  'guestCount' : bigint,
  'referenceId' : EntityId,
  'bookingType' : BookingType,
  'checkOut' : string,
  'paymentAmount' : bigint,
}
export interface CreateGuideInput {
  'bio' : string,
  'name' : string,
  'ratePerDay' : bigint,
  'isAvailable' : boolean,
  'imageUrl' : string,
  'experienceYears' : bigint,
  'specialization' : GuideSpecialization,
  'phoneNumber' : string,
  'languagesSpoken' : Array<string>,
}
export interface CreateHotelInput {
  'starRating' : bigint,
  'imageUrls' : Array<string>,
  'pricePerNight' : bigint,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'location' : string,
  'totalRooms' : bigint,
}
export interface CreatePlaceInput {
  'latitude' : [] | [number],
  'imageUrls' : Array<string>,
  'name' : string,
  'bestTimeToVisit' : string,
  'description' : string,
  'isFeatured' : boolean,
  'longitude' : [] | [number],
  'address' : string,
  'category' : PlaceCategory,
}
export interface CreateRestaurantInput {
  'ratingAverage' : number,
  'name' : string,
  'cuisineTypes' : Array<string>,
  'description' : string,
  'priceRange' : bigint,
  'hoursOpen' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'address' : string,
  'phone' : string,
  'location' : string,
}
export interface CreateRoomTypeInput {
  'pricePerNight' : bigint,
  'name' : string,
  'hotelId' : EntityId,
  'description' : string,
  'availability' : bigint,
  'maxGuests' : bigint,
}
export interface DashboardStats {
  'totalBookings' : bigint,
  'totalRestaurants' : bigint,
  'totalHotels' : bigint,
  'totalGuides' : bigint,
  'totalUsers' : bigint,
  'pendingReviews' : bigint,
  'totalPlaces' : bigint,
}
export type EntityId = bigint;
export interface Guide {
  'id' : EntityId,
  'bio' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'ratePerDay' : bigint,
  'isAvailable' : boolean,
  'imageUrl' : string,
  'experienceYears' : bigint,
  'specialization' : GuideSpecialization,
  'phoneNumber' : string,
  'languagesSpoken' : Array<string>,
}
export type GuideSpecialization = { 'nature' : null } |
  { 'adventure' : null } |
  { 'general' : null } |
  { 'heritage' : null };
export interface Hotel {
  'id' : EntityId,
  'starRating' : bigint,
  'imageUrls' : Array<string>,
  'pricePerNight' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'amenities' : Array<string>,
  'location' : string,
  'totalRooms' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface Place {
  'id' : EntityId,
  'latitude' : [] | [number],
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : Timestamp,
  'bestTimeToVisit' : string,
  'description' : string,
  'isFeatured' : boolean,
  'longitude' : [] | [number],
  'address' : string,
  'category' : PlaceCategory,
}
export type PlaceCategory = { 'other' : null } |
  { 'viewpoint' : null } |
  { 'beach' : null } |
  { 'temple' : null } |
  { 'waterfall' : null };
export interface Restaurant {
  'id' : EntityId,
  'ratingAverage' : number,
  'name' : string,
  'createdAt' : Timestamp,
  'cuisineTypes' : Array<string>,
  'description' : string,
  'priceRange' : bigint,
  'hoursOpen' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'address' : string,
  'phone' : string,
  'location' : string,
}
export interface Review {
  'id' : EntityId,
  'isApproved' : boolean,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'reviewerName' : string,
  'comment' : string,
  'targetType' : ReviewTargetType,
  'rating' : bigint,
  'targetId' : EntityId,
}
export type ReviewTargetType = { 'hotel' : null } |
  { 'guide' : null };
export interface RoomType {
  'id' : EntityId,
  'pricePerNight' : bigint,
  'name' : string,
  'hotelId' : EntityId,
  'description' : string,
  'availability' : bigint,
  'maxGuests' : bigint,
}
export interface SessionToken {
  'token' : string,
  'expiresAt' : Timestamp,
  'username' : string,
  'userId' : Principal,
  'fullName' : string,
  'mobileNumber' : string,
  'email' : string,
}
export type Timestamp = bigint;
export interface UpdateGuideInput {
  'id' : EntityId,
  'bio' : string,
  'name' : string,
  'ratePerDay' : bigint,
  'isAvailable' : boolean,
  'imageUrl' : string,
  'experienceYears' : bigint,
  'specialization' : GuideSpecialization,
  'phoneNumber' : string,
  'languagesSpoken' : Array<string>,
}
export interface UpdateHotelInput {
  'id' : EntityId,
  'starRating' : bigint,
  'imageUrls' : Array<string>,
  'pricePerNight' : bigint,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'location' : string,
  'totalRooms' : bigint,
}
export interface UpdatePlaceInput {
  'id' : EntityId,
  'latitude' : [] | [number],
  'imageUrls' : Array<string>,
  'name' : string,
  'bestTimeToVisit' : string,
  'description' : string,
  'isFeatured' : boolean,
  'longitude' : [] | [number],
  'address' : string,
  'category' : PlaceCategory,
}
export type UserId = Principal;
export interface _SERVICE {
  'approveReview' : ActorMethod<[EntityId], boolean>,
  'cancelBooking' : ActorMethod<[EntityId], boolean>,
  'claimAdmin' : ActorMethod<[], boolean>,
  'confirmBookingPayment' : ActorMethod<[EntityId, string, bigint], boolean>,
  'createBooking' : ActorMethod<[CreateBookingInput], Booking>,
  'createGuide' : ActorMethod<[CreateGuideInput], Guide>,
  'createHotel' : ActorMethod<[CreateHotelInput], Hotel>,
  'createPlace' : ActorMethod<[CreatePlaceInput], Place>,
  'createRestaurant' : ActorMethod<[CreateRestaurantInput], Restaurant>,
  'createRoomType' : ActorMethod<[CreateRoomTypeInput], RoomType>,
  'deleteGuide' : ActorMethod<[EntityId], boolean>,
  'deleteHotel' : ActorMethod<[EntityId], boolean>,
  'deletePlace' : ActorMethod<[EntityId], boolean>,
  'deleteRestaurant' : ActorMethod<[EntityId], boolean>,
  'getBooking' : ActorMethod<[EntityId], [] | [Booking]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getGuide' : ActorMethod<[EntityId], [] | [Guide]>,
  'getHotel' : ActorMethod<[EntityId], [] | [Hotel]>,
  'getPlace' : ActorMethod<[EntityId], [] | [Place]>,
  'getRestaurant' : ActorMethod<[EntityId], [] | [Restaurant]>,
  'getReviewsForTarget' : ActorMethod<
    [ReviewTargetType, EntityId],
    Array<Review>
  >,
  'getRoomTypesForHotel' : ActorMethod<[EntityId], Array<RoomType>>,
  'getUserBookings' : ActorMethod<[], Array<Booking>>,
  'isAdminCaller' : ActorMethod<[], boolean>,
  'listAllBookings' : ActorMethod<[], Array<Booking>>,
  'listFeaturedPlaces' : ActorMethod<[], Array<Place>>,
  'listFeaturedRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'listGuides' : ActorMethod<[], Array<Guide>>,
  'listHotels' : ActorMethod<[], Array<Hotel>>,
  'listPendingReviews' : ActorMethod<[], Array<Review>>,
  'listPlaces' : ActorMethod<[], Array<Place>>,
  'listRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'loginUser' : ActorMethod<
    [string, string],
    { 'ok' : SessionToken } |
      { 'err' : string }
  >,
  'logoutUser' : ActorMethod<[string], boolean>,
  'registerUser' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'rejectReview' : ActorMethod<[EntityId], boolean>,
  'searchGuides' : ActorMethod<
    [string, [] | [GuideSpecialization]],
    Array<Guide>
  >,
  'searchHotels' : ActorMethod<[string], Array<Hotel>>,
  'searchPlaces' : ActorMethod<[string, [] | [PlaceCategory]], Array<Place>>,
  'searchRestaurants' : ActorMethod<[string], Array<Restaurant>>,
  'updateGuide' : ActorMethod<[UpdateGuideInput], boolean>,
  'updateHotel' : ActorMethod<[UpdateHotelInput], boolean>,
  'updatePlace' : ActorMethod<[UpdatePlaceInput], boolean>,
  'validateSession' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];