/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface UpdateGuideInput {
    id: EntityId;
    bio: string;
    name: string;
    ratePerDay: bigint;
    isAvailable: boolean;
    imageUrl: string;
    experienceYears: bigint;
    specialization: GuideSpecialization;
    phoneNumber: string;
    languagesSpoken: Array<string>;
}
export type EntityId = bigint;
export interface CreatePlaceInput {
    latitude?: number;
    imageUrls: Array<string>;
    name: string;
    bestTimeToVisit: string;
    description: string;
    isFeatured: boolean;
    longitude?: number;
    address: string;
    category: PlaceCategory;
}
export interface CreateHotelInput {
    starRating: bigint;
    imageUrls: Array<string>;
    pricePerNight: bigint;
    name: string;
    description: string;
    amenities: Array<string>;
    location: string;
    totalRooms: bigint;
}
export interface RoomType {
    id: EntityId;
    pricePerNight: bigint;
    name: string;
    hotelId: EntityId;
    description: string;
    availability: bigint;
    maxGuests: bigint;
}
export interface Restaurant {
    id: EntityId;
    ratingAverage: number;
    name: string;
    createdAt: Timestamp;
    cuisineTypes: Array<string>;
    description: string;
    priceRange: bigint;
    hoursOpen: string;
    imageUrl: string;
    isFeatured: boolean;
    address: string;
    phone: string;
    location: string;
}
export interface Guide {
    id: EntityId;
    bio: string;
    name: string;
    createdAt: Timestamp;
    ratePerDay: bigint;
    isAvailable: boolean;
    imageUrl: string;
    experienceYears: bigint;
    specialization: GuideSpecialization;
    phoneNumber: string;
    languagesSpoken: Array<string>;
}
export interface UpdateHotelInput {
    id: EntityId;
    starRating: bigint;
    imageUrls: Array<string>;
    pricePerNight: bigint;
    name: string;
    description: string;
    amenities: Array<string>;
    location: string;
    totalRooms: bigint;
}
export interface Place {
    id: EntityId;
    latitude?: number;
    imageUrls: Array<string>;
    name: string;
    createdAt: Timestamp;
    bestTimeToVisit: string;
    description: string;
    isFeatured: boolean;
    longitude?: number;
    address: string;
    category: PlaceCategory;
}
export interface DashboardStats {
    totalBookings: bigint;
    totalRestaurants: bigint;
    totalHotels: bigint;
    totalGuides: bigint;
    totalUsers: bigint;
    pendingReviews: bigint;
    totalPlaces: bigint;
}
export type UserId = Principal;
export interface CreateRestaurantInput {
    ratingAverage: number;
    name: string;
    cuisineTypes: Array<string>;
    description: string;
    priceRange: bigint;
    hoursOpen: string;
    imageUrl: string;
    isFeatured: boolean;
    address: string;
    phone: string;
    location: string;
}
export interface CreateBookingInput {
    checkIn: string;
    paymentTransactionId?: string;
    guestCount: bigint;
    referenceId: EntityId;
    bookingType: BookingType;
    checkOut: string;
    paymentAmount: bigint;
}
export interface Hotel {
    id: EntityId;
    starRating: bigint;
    imageUrls: Array<string>;
    pricePerNight: bigint;
    name: string;
    createdAt: Timestamp;
    description: string;
    amenities: Array<string>;
    location: string;
    totalRooms: bigint;
}
export interface UpdatePlaceInput {
    id: EntityId;
    latitude?: number;
    imageUrls: Array<string>;
    name: string;
    bestTimeToVisit: string;
    description: string;
    isFeatured: boolean;
    longitude?: number;
    address: string;
    category: PlaceCategory;
}
export interface SessionToken {
    token: string;
    expiresAt: Timestamp;
    username: string;
    userId: Principal;
    fullName: string;
    mobileNumber: string;
    email: string;
}
export interface CreateRoomTypeInput {
    pricePerNight: bigint;
    name: string;
    hotelId: EntityId;
    description: string;
    availability: bigint;
    maxGuests: bigint;
}
export interface CreateGuideInput {
    bio: string;
    name: string;
    ratePerDay: bigint;
    isAvailable: boolean;
    imageUrl: string;
    experienceYears: bigint;
    specialization: GuideSpecialization;
    phoneNumber: string;
    languagesSpoken: Array<string>;
}
export interface Booking {
    id: EntityId;
    status: BookingStatus;
    checkIn: string;
    paymentStatus: PaymentStatus;
    referenceNumber: string;
    paymentTransactionId?: string;
    userId: UserId;
    guestCount: bigint;
    createdAt: Timestamp;
    referenceId: EntityId;
    bookingType: BookingType;
    checkOut: string;
    paymentAmount: bigint;
}
export interface Review {
    id: EntityId;
    isApproved: boolean;
    userId: UserId;
    createdAt: Timestamp;
    reviewerName: string;
    comment: string;
    targetType: ReviewTargetType;
    rating: bigint;
    targetId: EntityId;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum GuideSpecialization {
    nature = "nature",
    adventure = "adventure",
    general = "general",
    heritage = "heritage"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum PlaceCategory {
    other = "other",
    viewpoint = "viewpoint",
    beach = "beach",
    temple = "temple",
    waterfall = "waterfall"
}
export enum ReviewTargetType {
    hotel = "hotel",
    guide = "guide"
}
export interface backendInterface {
    approveReview(id: EntityId): Promise<boolean>;
    cancelBooking(id: EntityId): Promise<boolean>;
    claimAdmin(): Promise<boolean>;
    confirmBookingPayment(bookingId: EntityId, transactionId: string, amount: bigint): Promise<boolean>;
    createBooking(input: CreateBookingInput): Promise<Booking>;
    createGuide(input: CreateGuideInput): Promise<Guide>;
    createHotel(input: CreateHotelInput): Promise<Hotel>;
    createPlace(input: CreatePlaceInput): Promise<Place>;
    createRestaurant(input: CreateRestaurantInput): Promise<Restaurant>;
    createRoomType(input: CreateRoomTypeInput): Promise<RoomType>;
    deleteGuide(id: EntityId): Promise<boolean>;
    deleteHotel(id: EntityId): Promise<boolean>;
    deletePlace(id: EntityId): Promise<boolean>;
    deleteRestaurant(id: EntityId): Promise<boolean>;
    getBooking(id: EntityId): Promise<Booking | null>;
    getDashboardStats(): Promise<DashboardStats>;
    getGuide(id: EntityId): Promise<Guide | null>;
    getHotel(id: EntityId): Promise<Hotel | null>;
    getPlace(id: EntityId): Promise<Place | null>;
    getRestaurant(id: EntityId): Promise<Restaurant | null>;
    getReviewsForTarget(targetType: ReviewTargetType, targetId: EntityId): Promise<Array<Review>>;
    getRoomTypesForHotel(hotelId: EntityId): Promise<Array<RoomType>>;
    getUserBookings(): Promise<Array<Booking>>;
    isAdminCaller(): Promise<boolean>;
    listAllBookings(): Promise<Array<Booking>>;
    listFeaturedPlaces(): Promise<Array<Place>>;
    listFeaturedRestaurants(): Promise<Array<Restaurant>>;
    listGuides(): Promise<Array<Guide>>;
    listHotels(): Promise<Array<Hotel>>;
    listPendingReviews(): Promise<Array<Review>>;
    listPlaces(): Promise<Array<Place>>;
    listRestaurants(): Promise<Array<Restaurant>>;
    loginUser(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: SessionToken;
    } | {
        __kind__: "err";
        err: string;
    }>;
    logoutUser(token: string): Promise<boolean>;
    registerUser(username: string, password: string, fullName: string, mobileNumber: string, email: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    rejectReview(id: EntityId): Promise<boolean>;
    searchGuides(term: string, specialization: GuideSpecialization | null): Promise<Array<Guide>>;
    searchHotels(term: string): Promise<Array<Hotel>>;
    searchPlaces(term: string, category: PlaceCategory | null): Promise<Array<Place>>;
    searchRestaurants(term: string): Promise<Array<Restaurant>>;
    updateGuide(input: UpdateGuideInput): Promise<boolean>;
    updateHotel(input: UpdateHotelInput): Promise<boolean>;
    updatePlace(input: UpdatePlaceInput): Promise<boolean>;
    validateSession(token: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, BookingType as _BookingType, CreateBookingInput as _CreateBookingInput, CreateGuideInput as _CreateGuideInput, CreatePlaceInput as _CreatePlaceInput, EntityId as _EntityId, Guide as _Guide, GuideSpecialization as _GuideSpecialization, Hotel as _Hotel, PaymentStatus as _PaymentStatus, Place as _Place, PlaceCategory as _PlaceCategory, Restaurant as _Restaurant, Review as _Review, ReviewTargetType as _ReviewTargetType, SessionToken as _SessionToken, Timestamp as _Timestamp, UpdateGuideInput as _UpdateGuideInput, UpdatePlaceInput as _UpdatePlaceInput, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveReview(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReview(arg0);
            return result;
        }
    }
    async cancelBooking(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async claimAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return result;
        }
    }
    async confirmBookingPayment(arg0: EntityId, arg1: string, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBookingPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBookingPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async createBooking(arg0: CreateBookingInput): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_CreateBookingInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Booking_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_CreateBookingInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Booking_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGuide(arg0: CreateGuideInput): Promise<Guide> {
        if (this.processError) {
            try {
                const result = await this.actor.createGuide(to_candid_CreateGuideInput_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Guide_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGuide(to_candid_CreateGuideInput_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Guide_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createHotel(arg0: CreateHotelInput): Promise<Hotel> {
        if (this.processError) {
            try {
                const result = await this.actor.createHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHotel(arg0);
            return result;
        }
    }
    async createPlace(arg0: CreatePlaceInput): Promise<Place> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlace(to_candid_CreatePlaceInput_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Place_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlace(to_candid_CreatePlaceInput_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Place_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRestaurant(arg0: CreateRestaurantInput): Promise<Restaurant> {
        if (this.processError) {
            try {
                const result = await this.actor.createRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRestaurant(arg0);
            return result;
        }
    }
    async createRoomType(arg0: CreateRoomTypeInput): Promise<RoomType> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoomType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoomType(arg0);
            return result;
        }
    }
    async deleteGuide(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGuide(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGuide(arg0);
            return result;
        }
    }
    async deleteHotel(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHotel(arg0);
            return result;
        }
    }
    async deletePlace(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlace(arg0);
            return result;
        }
    }
    async deleteRestaurant(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRestaurant(arg0);
            return result;
        }
    }
    async getBooking(arg0: EntityId): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getGuide(arg0: EntityId): Promise<Guide | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuide(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuide(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotel(arg0: EntityId): Promise<Hotel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotel(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotel(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlace(arg0: EntityId): Promise<Place | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlace(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlace(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurant(arg0: EntityId): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurant(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurant(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsForTarget(arg0: ReviewTargetType, arg1: EntityId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsForTarget(to_candid_ReviewTargetType_n36(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsForTarget(to_candid_ReviewTargetType_n36(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomTypesForHotel(arg0: EntityId): Promise<Array<RoomType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomTypesForHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomTypesForHotel(arg0);
            return result;
        }
    }
    async getUserBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminCaller(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminCaller();
            return result;
        }
    }
    async listAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBookings();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBookings();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFeaturedPlaces(): Promise<Array<Place>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeaturedPlaces();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeaturedPlaces();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFeaturedRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeaturedRestaurants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeaturedRestaurants();
            return result;
        }
    }
    async listGuides(): Promise<Array<Guide>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGuides();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGuides();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHotels(): Promise<Array<Hotel>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHotels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHotels();
            return result;
        }
    }
    async listPendingReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingReviews();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingReviews();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPlaces(): Promise<Array<Place>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlaces();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlaces();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRestaurants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRestaurants();
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: SessionToken;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async logoutUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutUser(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectReview(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectReview(arg0);
            return result;
        }
    }
    async searchGuides(arg0: string, arg1: GuideSpecialization | null): Promise<Array<Guide>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGuides(arg0, to_candid_opt_n46(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGuides(arg0, to_candid_opt_n46(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchHotels(arg0: string): Promise<Array<Hotel>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchHotels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchHotels(arg0);
            return result;
        }
    }
    async searchPlaces(arg0: string, arg1: PlaceCategory | null): Promise<Array<Place>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPlaces(arg0, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPlaces(arg0, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchRestaurants(arg0: string): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRestaurants(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRestaurants(arg0);
            return result;
        }
    }
    async updateGuide(arg0: UpdateGuideInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGuide(to_candid_UpdateGuideInput_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGuide(to_candid_UpdateGuideInput_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateHotel(arg0: UpdateHotelInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHotel(arg0);
            return result;
        }
    }
    async updatePlace(arg0: UpdatePlaceInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlace(to_candid_UpdatePlaceInput_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlace(to_candid_UpdatePlaceInput_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async validateSession(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_BookingType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingType): BookingType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_GuideSpecialization_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuideSpecialization): GuideSpecialization {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Guide_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Guide): Guide {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PlaceCategory_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaceCategory): PlaceCategory {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Place_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Place): Place {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewTargetType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewTargetType): ReviewTargetType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Guide]): Guide | null {
    return value.length === 0 ? null : from_candid_Guide_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Hotel]): Hotel | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Place]): Place | null {
    return value.length === 0 ? null : from_candid_Place_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Restaurant]): Restaurant | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    bio: string;
    name: string;
    createdAt: _Timestamp;
    ratePerDay: bigint;
    isAvailable: boolean;
    imageUrl: string;
    experienceYears: bigint;
    specialization: _GuideSpecialization;
    phoneNumber: string;
    languagesSpoken: Array<string>;
}): {
    id: EntityId;
    bio: string;
    name: string;
    createdAt: Timestamp;
    ratePerDay: bigint;
    isAvailable: boolean;
    imageUrl: string;
    experienceYears: bigint;
    specialization: GuideSpecialization;
    phoneNumber: string;
    languagesSpoken: Array<string>;
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        createdAt: value.createdAt,
        ratePerDay: value.ratePerDay,
        isAvailable: value.isAvailable,
        imageUrl: value.imageUrl,
        experienceYears: value.experienceYears,
        specialization: from_candid_GuideSpecialization_n20(_uploadFile, _downloadFile, value.specialization),
        phoneNumber: value.phoneNumber,
        languagesSpoken: value.languagesSpoken
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    latitude: [] | [number];
    imageUrls: Array<string>;
    name: string;
    createdAt: _Timestamp;
    bestTimeToVisit: string;
    description: string;
    isFeatured: boolean;
    longitude: [] | [number];
    address: string;
    category: _PlaceCategory;
}): {
    id: EntityId;
    latitude?: number;
    imageUrls: Array<string>;
    name: string;
    createdAt: Timestamp;
    bestTimeToVisit: string;
    description: string;
    isFeatured: boolean;
    longitude?: number;
    address: string;
    category: PlaceCategory;
} {
    return {
        id: value.id,
        latitude: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.latitude)),
        imageUrls: value.imageUrls,
        name: value.name,
        createdAt: value.createdAt,
        bestTimeToVisit: value.bestTimeToVisit,
        description: value.description,
        isFeatured: value.isFeatured,
        longitude: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.longitude)),
        address: value.address,
        category: from_candid_PlaceCategory_n29(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    isApproved: boolean;
    userId: _UserId;
    createdAt: _Timestamp;
    reviewerName: string;
    comment: string;
    targetType: _ReviewTargetType;
    rating: bigint;
    targetId: _EntityId;
}): {
    id: EntityId;
    isApproved: boolean;
    userId: UserId;
    createdAt: Timestamp;
    reviewerName: string;
    comment: string;
    targetType: ReviewTargetType;
    rating: bigint;
    targetId: EntityId;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        userId: value.userId,
        createdAt: value.createdAt,
        reviewerName: value.reviewerName,
        comment: value.comment,
        targetType: from_candid_ReviewTargetType_n40(_uploadFile, _downloadFile, value.targetType),
        rating: value.rating,
        targetId: value.targetId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: _BookingStatus;
    checkIn: string;
    paymentStatus: _PaymentStatus;
    referenceNumber: string;
    paymentTransactionId: [] | [string];
    userId: _UserId;
    guestCount: bigint;
    createdAt: _Timestamp;
    referenceId: _EntityId;
    bookingType: _BookingType;
    checkOut: string;
    paymentAmount: bigint;
}): {
    id: EntityId;
    status: BookingStatus;
    checkIn: string;
    paymentStatus: PaymentStatus;
    referenceNumber: string;
    paymentTransactionId?: string;
    userId: UserId;
    guestCount: bigint;
    createdAt: Timestamp;
    referenceId: EntityId;
    bookingType: BookingType;
    checkOut: string;
    paymentAmount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n7(_uploadFile, _downloadFile, value.status),
        checkIn: value.checkIn,
        paymentStatus: from_candid_PaymentStatus_n9(_uploadFile, _downloadFile, value.paymentStatus),
        referenceNumber: value.referenceNumber,
        paymentTransactionId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.paymentTransactionId)),
        userId: value.userId,
        guestCount: value.guestCount,
        createdAt: value.createdAt,
        referenceId: value.referenceId,
        bookingType: from_candid_BookingType_n12(_uploadFile, _downloadFile, value.bookingType),
        checkOut: value.checkOut,
        paymentAmount: value.paymentAmount
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hotel: null;
} | {
    guide: null;
}): ReviewTargetType {
    return "hotel" in value ? ReviewTargetType.hotel : "guide" in value ? ReviewTargetType.guide : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nature: null;
} | {
    adventure: null;
} | {
    general: null;
} | {
    heritage: null;
}): GuideSpecialization {
    return "nature" in value ? GuideSpecialization.nature : "adventure" in value ? GuideSpecialization.adventure : "general" in value ? GuideSpecialization.general : "heritage" in value ? GuideSpecialization.heritage : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    viewpoint: null;
} | {
    beach: null;
} | {
    temple: null;
} | {
    waterfall: null;
}): PlaceCategory {
    return "other" in value ? PlaceCategory.other : "viewpoint" in value ? PlaceCategory.viewpoint : "beach" in value ? PlaceCategory.beach : "temple" in value ? PlaceCategory.temple : "waterfall" in value ? PlaceCategory.waterfall : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionToken;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Place>): Array<Place> {
    return value.map((x)=>from_candid_Place_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Guide>): Array<Guide> {
    return value.map((x)=>from_candid_Guide_n18(_uploadFile, _downloadFile, x));
}
function to_candid_BookingType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingType): _BookingType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateBookingInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBookingInput): _CreateBookingInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateGuideInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateGuideInput): _CreateGuideInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_CreatePlaceInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePlaceInput): _CreatePlaceInput {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_GuideSpecialization_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideSpecialization): _GuideSpecialization {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceCategory): _PlaceCategory {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewTargetType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewTargetType): _ReviewTargetType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateGuideInput_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateGuideInput): _UpdateGuideInput {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UpdatePlaceInput_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdatePlaceInput): _UpdatePlaceInput {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideSpecialization | null): [] | [_GuideSpecialization] {
    return value === null ? candid_none() : candid_some(to_candid_GuideSpecialization_n16(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceCategory | null): [] | [_PlaceCategory] {
    return value === null ? candid_none() : candid_some(to_candid_PlaceCategory_n24(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    name: string;
    ratePerDay: bigint;
    isAvailable: boolean;
    imageUrl: string;
    experienceYears: bigint;
    specialization: GuideSpecialization;
    phoneNumber: string;
    languagesSpoken: Array<string>;
}): {
    bio: string;
    name: string;
    ratePerDay: bigint;
    isAvailable: boolean;
    imageUrl: string;
    experienceYears: bigint;
    specialization: _GuideSpecialization;
    phoneNumber: string;
    languagesSpoken: Array<string>;
} {
    return {
        bio: value.bio,
        name: value.name,
        ratePerDay: value.ratePerDay,
        isAvailable: value.isAvailable,
        imageUrl: value.imageUrl,
        experienceYears: value.experienceYears,
        specialization: to_candid_GuideSpecialization_n16(_uploadFile, _downloadFile, value.specialization),
        phoneNumber: value.phoneNumber,
        languagesSpoken: value.languagesSpoken
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkIn: string;
    paymentTransactionId?: string;
    guestCount: bigint;
    referenceId: EntityId;
    bookingType: BookingType;
    checkOut: string;
    paymentAmount: bigint;
}): {
    checkIn: string;
    paymentTransactionId: [] | [string];
    guestCount: bigint;
    referenceId: _EntityId;
    bookingType: _BookingType;
    checkOut: string;
    paymentAmount: bigint;
} {
    return {
        checkIn: value.checkIn,
        paymentTransactionId: value.paymentTransactionId ? candid_some(value.paymentTransactionId) : candid_none(),
        guestCount: value.guestCount,
        referenceId: value.referenceId,
        bookingType: to_candid_BookingType_n3(_uploadFile, _downloadFile, value.bookingType),
        checkOut: value.checkOut,
        paymentAmount: value.paymentAmount
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude?: number;
    imageUrls: Array<string>;
    name: string;
    bestTimeToVisit: string;
    description: string;
    isFeatured: boolean;
    longitude?: number;
    address: string;
    category: PlaceCategory;
}): {
    latitude: [] | [number];
    imageUrls: Array<string>;
    name: string;
    bestTimeToVisit: string;
    description: string;
    isFeatured: boolean;
    longitude: [] | [number];
    address: string;
    category: _PlaceCategory;
} {
    return {
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        imageUrls: value.imageUrls,
        name: value.name,
        bestTimeToVisit: value.bestTimeToVisit,
        description: value.description,
        isFeatured: value.isFeatured,
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        address: value.address,
        category: to_candid_PlaceCategory_n24(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EntityId;
    bio: string;
    name: string;
    ratePerDay: bigint;
    isAvailable: boolean;
    imageUrl: string;
    experienceYears: bigint;
    specialization: GuideSpecialization;
    phoneNumber: string;
    languagesSpoken: Array<string>;
}): {
    id: _EntityId;
    bio: string;
    name: string;
    ratePerDay: bigint;
    isAvailable: boolean;
    imageUrl: string;
    experienceYears: bigint;
    specialization: _GuideSpecialization;
    phoneNumber: string;
    languagesSpoken: Array<string>;
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        ratePerDay: value.ratePerDay,
        isAvailable: value.isAvailable,
        imageUrl: value.imageUrl,
        experienceYears: value.experienceYears,
        specialization: to_candid_GuideSpecialization_n16(_uploadFile, _downloadFile, value.specialization),
        phoneNumber: value.phoneNumber,
        languagesSpoken: value.languagesSpoken
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EntityId;
    latitude?: number;
    imageUrls: Array<string>;
    name: string;
    bestTimeToVisit: string;
    description: string;
    isFeatured: boolean;
    longitude?: number;
    address: string;
    category: PlaceCategory;
}): {
    id: _EntityId;
    latitude: [] | [number];
    imageUrls: Array<string>;
    name: string;
    bestTimeToVisit: string;
    description: string;
    isFeatured: boolean;
    longitude: [] | [number];
    address: string;
    category: _PlaceCategory;
} {
    return {
        id: value.id,
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        imageUrls: value.imageUrls,
        name: value.name,
        bestTimeToVisit: value.bestTimeToVisit,
        description: value.description,
        isFeatured: value.isFeatured,
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        address: value.address,
        category: to_candid_PlaceCategory_n24(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideSpecialization): {
    nature: null;
} | {
    adventure: null;
} | {
    general: null;
} | {
    heritage: null;
} {
    return value == GuideSpecialization.nature ? {
        nature: null
    } : value == GuideSpecialization.adventure ? {
        adventure: null
    } : value == GuideSpecialization.general ? {
        general: null
    } : value == GuideSpecialization.heritage ? {
        heritage: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceCategory): {
    other: null;
} | {
    viewpoint: null;
} | {
    beach: null;
} | {
    temple: null;
} | {
    waterfall: null;
} {
    return value == PlaceCategory.other ? {
        other: null
    } : value == PlaceCategory.viewpoint ? {
        viewpoint: null
    } : value == PlaceCategory.beach ? {
        beach: null
    } : value == PlaceCategory.temple ? {
        temple: null
    } : value == PlaceCategory.waterfall ? {
        waterfall: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewTargetType): {
    hotel: null;
} | {
    guide: null;
} {
    return value == ReviewTargetType.hotel ? {
        hotel: null
    } : value == ReviewTargetType.guide ? {
        guide: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
